### ISSUE TITLE
buggy with certain sentences

### ISSUE THREAD

**Issue by bsharpataz** [ml4ai/automates#27]
`With an RMSE of 22.8%, drastic discrepancies were found in the comparison of Ref-ET ETo and ETpm from DSSAT-CSM version 4.5 for Arizona conditions (fig. 1a).`

```[info] play.api.Play - Application started (Dev)
Processing sentence : With an RMSE of 22.8%, drastic discrepancies were found in the comparison of Ref-ET ETo and ETpm from DSSAT-CSM version 4.5 for Arizona conditions (fig. 1a).
DOC : org.clulab.processors.corenlp.CoreNLPDocument@6992ebed
[error] application -

! @7am4d9lji - Internal server error, for (GET) [/parseSentence?sent=With+an+RMSE+of+22.8%25%2C+drastic+discrepancies+were+found+in+the+comparison+of+Ref-ET+ETo+and+ETpm+from+DSSAT-CSM+version+4.5+for+Arizona+conditions+(fig.+1a).&showEverything=true] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NoSuchElementException: key not found: type]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:250)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Caused by: java.util.NoSuchElementException: key not found: type
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ujson.Value$Selector$StringSelector.apply(Value.scala:97)
	at ujson.Value.apply(Value.scala:62)
	at ujson.Value.apply$(Value.scala:62)
	at ujson.Obj.apply(Value.scala:190)
```

**Comment by bsharpataz** [comment]
grobid output:
```{
    "runtime": 22,
    "measurements": [
        {
            "type": "value",
            "quantity": {
                "rawValue": "22.8",
                "rawUnit": {
                    "name": "%",
                    "type": "fraction",
                    "system": "non SI",
                    "offsetStart": 20,
                    "offsetEnd": 21
                },
                "parsedValue": {
                    "numeric": 22.8,
                    "structure": {
                        "type": "NUMBER",
                        "formatted": "22.8"
                    },
                    "parsed": "22.8"
                },
                "normalizedQuantity": 0.228,
                "normalizedUnit": {
                    "name": "one"
                },
                "offsetStart": 16,
                "offsetEnd": 20,
                "quantified": {
                    "rawName": "an RMSE of",
                    "normalizedName": "rmse",
                    "offsetStart": 5,
                    "offsetEnd": 15
                }
            },
            "quantified": {
                "rawName": "an RMSE of",
                "normalizedName": "rmse",
                "offsetStart": 5,
                "offsetEnd": 15
            }
        }
    ]
}
```

**Comment by bsharpataz** [comment]
need to make this an option?
https://github.com/ml4ai/automates/blob/master/text_reading/src/main/scala/org/clulab/aske/automates/quantities/GrobidQuantitiesClient.scala#L61

**Comment by maxaalexeeva** [comment]
@bsharpataz Tried fixing this but haven't made it work yet. This is what I tried:

Made line 61 an option, then the same error occurred (key not found), but for the key "system". Made that an option as well like this:
```
  def mkUnit(json: ujson.Js): UnitOfMeasurement = {
    val name = json("name").str
    //val unitType = json("type").str
    val unitType = if (json.obj.keySet contains "type") mkUnit(json).unitType else None
    //val system = json("system").str
    val system = if (json.obj.keySet contains "system") mkUnit(json).system else None
    val offset = if (json.obj.keySet contains "offsetStart") Some(mkOffset(json)) else None
    UnitOfMeasurement(name, unitType, system, offset)
  }
```
and updated the UnitOfMeasurement class like this in Measurement.scala:
```
case class UnitOfMeasurement(
  name: String,
  unitType: Option[String],
  system: Option[String],
  offset: Option[Offset]
)
```
 The tests ran through (and the one where the error occurred sort of worked, I think), but got an error in the webapp:

```
Processing sentence : With an RMSE of 22.8%, drastic discrepancies were found in the comparison of Ref-ET ETo and ETpm from DSSAT-CSM version 4.5 for Arizona conditions (fig. 1a).
DOC : org.clulab.processors.corenlp.CoreNLPDocument@6eed07a4
Uncaught error from thread [play-dev-mode-akka.actor.default-dispatcher-4]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[play-dev-mode]
java.lang.StackOverflowError
	at scala.collection.mutable.HashTable.findEntry0(HashTable.scala:138)
	at scala.collection.mutable.HashTable.findEntry(HashTable.scala:135)
	at scala.collection.mutable.HashTable.findEntry$(HashTable.scala:134)
	at scala.collection.mutable.LinkedHashMap.findEntry(LinkedHashMap.scala:49)
	at scala.collection.mutable.LinkedHashMap.get(LinkedHashMap.scala:65)
	at scala.collection.MapLike.apply(MapLike.scala:140)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ujson.Value$Selector$StringSelector.apply(Value.scala:97)
	at ujson.Value.apply(Value.scala:62)
	at ujson.Value.apply$(Value.scala:62)
	at ujson.Obj.apply(Value.scala:190)
	at org.clulab.aske.automates.quantities.GrobidQuantitiesClient.mkUnit(GrobidQuantitiesClient.scala:60)
```

**Comment by bsharpataz** [comment]
@maxaalexeeva -- I think i have this mostly done -- but the number of exceptions we seem to have to catch is worrisome (fyi @marcovzla )
I will PR my for-now "solution" but also note that I think we will need to switch to processing a sentence at a time through grobid (not a document) because we _not rarely_ get a ujson.ParseException when we give the text to grobid, and if we keep processing at a Document level we will lose the whole Document rather than just the current sentence).  There may be an alternative way to catch the exception too...
Can you all remember why we decided doc vs sentence in the first place?  Are there grobid-found things that cross sentences?

**Comment by maxaalexeeva** [comment]
@bsharpataz wasn't doc-vs-sent processing one of the "let's do it this way for now, but then revisit it" decisions? I can't remember anything that would stop us from doing it one sentence at a time... I can't think of any obvious examples when grobid entities would cross sentences.. Unless there's a period in some unit and the sentence gets accidentally split into two...

**Comment by bsharpataz** [comment]
that may have been it actually.... hmmm.......
