### ISSUE TITLE
expansion expects a TextBoundMention

### ISSUE THREAD

**Issue by BeckySharp** [ml4ai/automates#41]
Should we need to modify it to handle other mention types?  Or not expand?

with text: `For this research Tx = 10 mm d−1, Lsc = −1100 J kg−1 and Lpwp = −2000 J kg−1.`
(variable test t9b)

``` 
[info]   java.lang.ClassCastException: org.clulab.odin.RelationMention cannot be cast to org.clulab.odin.TextBoundMention
[info]   at org.clulab.aske.automates.actions.ExpansionHandler.expand(ExpansionHandler.scala:136)
[info]   at org.clulab.aske.automates.actions.ExpansionHandler.expandIfNotAvoid(ExpansionHandler.scala:95)
[info]   at org.clulab.aske.automates.actions.ExpansionHandler.$anonfun$expandArgs$4(ExpansionHandler.scala:67)
[info]   at org.clulab.aske.automates.actions.ExpansionHandler.$anonfun$expandArgs$4$adapted(ExpansionHandler.scala:66)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:929)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:929)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[info]   at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[info]   at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
```

**Comment by maxaalexeeva** [comment]
We will probably want to expand not only TextBoundMentions eventually (like if we want to extract definitions that include parameter setting, e.g., X is Y at <parameter setting>)? What would be expanded here? @bsharpataz

**Comment by maxaalexeeva** [comment]
We expand descriptions and functions, only the args, and the args are TextBoundMentions, so it's fine to just expand those for now. The error has been handled (just return the original mention in case it's not a text bound mention).
