### ISSUE TITLE
We are not handling listc

### ISSUE THREAD

**Issue by maxaalexeeva** [ml4ai/automates#8]
This sentence:
`The height of the chair was 100-150 cm and it was between 2700.5 and 3000 mm in length.`

stack trace:
```
Exception in thread "main" java.lang.RuntimeException: unsupported measurement type 'listc'
	at org.clulab.aske.automates.quantities.GrobidQuantitiesClient.mkMeasurement(GrobidQuantitiesClient.scala:30)
	at org.clulab.aske.automates.quantities.GrobidQuantitiesClient.$anonfun$getMeasurements$1(GrobidQuantitiesClient.scala:24)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.clulab.aske.automates.quantities.GrobidQuantitiesClient.getMeasurements(GrobidQuantitiesClient.scala:24)
	at org.clulab.aske.automates.entities.GrobidEntityFinder.extract(GrobidEntityFinder.scala:19)
	at org.clulab.aske.automates.entities.TestStuff$.main(GrobidEntityFinder.scala:156)
	at org.clulab.aske.automates.entities.TestStuff.main(GrobidEntityFinder.scala)

Process finished with exit code 1
```

anything _else_ we're not handling????? (assuredly)

**Comment by maxaalexeeva** [comment]
Addressed in PR #43 (temp fix)
